/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAnalyzePetRouteImport } from './routes/api/analyze-pet'
import { Route as ApiPublicPetEventRouteImport } from './routes/api/public/pet-event'

const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzePetRoute = ApiAnalyzePetRouteImport.update({
  id: '/api/analyze-pet',
  path: '/api/analyze-pet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPetEventRoute = ApiPublicPetEventRouteImport.update({
  id: '/api/public/pet-event',
  path: '/api/public/pet-event',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/metrics': typeof MetricsRoute
  '/api/analyze-pet': typeof ApiAnalyzePetRoute
  '/api/public/pet-event': typeof ApiPublicPetEventRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/metrics': typeof MetricsRoute
  '/api/analyze-pet': typeof ApiAnalyzePetRoute
  '/api/public/pet-event': typeof ApiPublicPetEventRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/metrics': typeof MetricsRoute
  '/api/analyze-pet': typeof ApiAnalyzePetRoute
  '/api/public/pet-event': typeof ApiPublicPetEventRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/metrics' | '/api/analyze-pet' | '/api/public/pet-event'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/metrics' | '/api/analyze-pet' | '/api/public/pet-event'
  id:
    | '__root__'
    | '/'
    | '/metrics'
    | '/api/analyze-pet'
    | '/api/public/pet-event'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MetricsRoute: typeof MetricsRoute
  ApiAnalyzePetRoute: typeof ApiAnalyzePetRoute
  ApiPublicPetEventRoute: typeof ApiPublicPetEventRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-pet': {
      id: '/api/analyze-pet'
      path: '/api/analyze-pet'
      fullPath: '/api/analyze-pet'
      preLoaderRoute: typeof ApiAnalyzePetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pet-event': {
      id: '/api/public/pet-event'
      path: '/api/public/pet-event'
      fullPath: '/api/public/pet-event'
      preLoaderRoute: typeof ApiPublicPetEventRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MetricsRoute: MetricsRoute,
  ApiAnalyzePetRoute: ApiAnalyzePetRoute,
  ApiPublicPetEventRoute: ApiPublicPetEventRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
